version: "3.8"

services:
  sut:
    image: ${IMAGE_TAG}
    entrypoint: /bin/bash -c
    working_dir: "/app"
    command:
      - coverage run -m pytest access_guard/ && coverage xml -o /app/coverage/coverage.xml
    stdin_open: true
    tty: true
    environment:
      COVERAGE_RCFILE: /app/setup.cfg
    volumes:
      - ./coverage:/app/coverage
