version: "3.8"

services:
  sut:
    image: ${IMAGE_TAG}
    entrypoint: /bin/bash -c
    working_dir: "/app"
    command:
      - pytest --cov-report=xml:/app/coverage/coverage.xml access_guard/
    stdin_open: true
    tty: true
    environment:
      COVERAGE_RCFILE: /app/setup.cfg
    volumes:
      - ./coverage:/app/coverage
      - ./.mypy_cache:/app/.mypy_cache
