[tool.black]
line-length = 88
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.nox
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''

[tool.isort]
line_length = 88
known_first_party = "access_guard/"
multi_line_output = 3
combine_as_imports = true
include_trailing_comma = true
force_grid_wrap = 0

[tool.pytest.ini_options]
addopts = "--cov=access_guard --cov-report=term-missing --no-cov-on-fail -rxXs -v"
testpaths = [
  "access_guard/tests",
]

[tool.coverage.run]
branch = true
omit = [
  "*/venv/*",
  "*/__main__.py",
]

[tool.coverage.report]
skip_covered = true
show_missing = true
exclude_lines = [
  "pragma: no cover",
  # ignore non-implementations
  '^\s*\.\.\.',
  "if TYPE_CHECKING:",
  "raise NotImplementedError",
  '^@skip\(',
]

[tool.mypy]
python_version = "3.10"
pretty = true
files = "access_guard"
show_error_codes = true
no_implicit_reexport = true
no_implicit_optional = true
strict_equality = true
strict_optional = true
check_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_defs = true
ignore_missing_imports = false
warn_unused_configs = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
warn_unreachable = true

[[tool.mypy.overrides]]
module = "*.tests.*"
ignore_errors = true

[[tool.mypy.overrides]]
module = [
  "factory.*",
  "uvicorn.*"
]
ignore_missing_imports = true
