version: "3.8"

services:
  traefik:
    image: traefik:v2.5
    command: |
      --providers.docker
      --providers.docker.exposedByDefault=false
      --log.level=INFO
      --accesslog=true
      --entryPoints.web.address=:80
      --api.insecure=true
      --api.dashboard=true
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.enable: "true"
      traefik.http.routers.api.rule: "Host(`traefik.localhost.com`)"
      traefik.http.routers.api.service: "api@internal"

  whoami:
    image: traefik/whoami
    labels:
      traefik.enable: "true"
      traefik.http.routers.whoami.rule: "Host(`whoami.localhost.com`)"
      traefik.http.routers.whoami.priority: "1"
      traefik.http.routers.whoami.middlewares: "access-guard@docker"

  access-guard:
    image: access-guard
    command: [
      ".*@test\\.com$$",
      "--secret", "supersecret",
      # Match the --auth-host value with the traefik rule
      "--auth-host", "http://whoami.localhost.com/access-guard/",
      "--trusted-hosts", "access-guard", "whoami.localhost.com",
      "--cookie-domain", "localhost.com",
      "--email-host", "mailhog",
      "--email-port", "1025",
      "--from-email", "access-guard@local.com"
      ]
    depends_on:
      - mailhog
    labels:
      traefik.enable: "true"
      traefik.http.routers.access-guard.rule: "Host(`whoami.localhost.com`) && PathPrefix(`/access-guard/`)"
      traefik.http.routers.access-guard.priority: "9999"
      traefik.http.routers.access-guard.service: "access-guard"
      traefik.http.middlewares.access-guard.forwardauth.address: "http://access-guard:8585/access-guard/auth"
      traefik.http.services.access-guard.loadbalancer.server.port: "8585"

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
