---

name: Docker cache

on:
  push:
    branches:
      - master

env:
  DOCKER_CACHE_TAG: ghcr.io/${{ github.repository_owner }}/access-guard:cache

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.6.3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          cache-from: type=registry,ref=${{ env.DOCKER_CACHE_TAG }}
          cache-to: type=registry,ref=${{ env.DOCKER_CACHE_TAG }},mode=max
          target: dev
          context: .
          push: true
          tags: ${{ env.DOCKER_CACHE_TAG }}
