---

name: Docker cache

on:
  push:
    branches:
      - master

env:
  RUNTIME_CACHE_TAG: ghcr.io/${{ github.repository_owner }}/access-guard:runtime-cache
  DEV_CACHE_TAG: ghcr.io/${{ github.repository_owner }}/access-guard:dev-cache

jobs:
  source-hash:
    name: Get source hash
    uses: flaeppe/access-guard/.github/workflows/source_hash.yml@master

  push-base-cache:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.6.3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build runtime image
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile-base
          cache-from: type=registry,ref=${{ env.RUNTIME_CACHE_TAG }}
          cache-to: type=registry,ref=${{ env.RUNTIME_CACHE_TAG }},mode=max
          context: .
          push: true
          tags: ${{ env.RUNTIME_CACHE_TAG }}

  push-dev-cache:
    runs-on: ubuntu-latest
    needs: source-hash
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.6.3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build dev image
        uses: docker/build-push-action@v2
        with:
          cache-from: type=registry,ref=${{ env.DEV_CACHE_TAG }}
          cache-to: type=registry,ref=${{ env.DEV_CACHE_TAG }},mode=max
          context: .
          target: dev
          push: true
          build-args: BASE_IMAGE=ghcr.io/${{ github.repository_owner }}/access-guard:${{ needs.source-hash.outputs.source_hash }}
          tags: ${{ env.DEV_CACHE_TAG }}
