---

name: Publish images

on:
  pull_request:
    branches:
      - master
    types: [closed]

env:
  PR_TAG: ghcr.io/${{ github.repository_owner }}/access-guard:pr-${{ github.event.number }}
  EDGE_TAG: ghcr.io/${{ github.repository_owner }}/access-guard:edge

jobs:
  source-hash:
    if: github.event.pull_request.merged == true
    uses: flaeppe/access-guard/.github/workflows/source_hash.yml@master

  push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    needs: source-hash
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.6.3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull PR image
        run: |
          docker pull ${{ env.PR_TAG }}
      - name: Build and push edge image
        uses: docker/build-push-action@v2
        with:
          target: release
          context: .
          build-args: |
            SOURCE_HASH=${{ needs.source-hash.outputs.source_hash }}
            BUILD_VERSION=${{ github.sha }}
          push: true
          tags: |
            ${{ env.EDGE_TAG }}
      - name: Build and push runtime image
        uses: docker/build-push-action@v2
        with:
          target: runtime
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/access-guard:${{ needs.source-hash.outputs.source_hash }}
