---

name: Publish Docker images

on:
  push:
    branches:
      - master

env:
  EDGE_TAG: ghcr.io/${{ github.repository_owner }}/access-guard:edge

jobs:
  source-hash:
    uses: flaeppe/access-guard/.github/workflows/source_hash.yml@master

  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    needs: source-hash
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.6.3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push edge image
        uses: docker/build-push-action@v2
        with:
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/access-guard:${{ needs.source-hash.outputs.source_hash }}
          target: release
          context: .
          build-args: |
            SOURCE_HASH=${{ needs.source-hash.outputs.source_hash }}
            BUILD_VERSION=${{ github.sha }}
          push: true
          tags: |
            ${{ env.EDGE_TAG }}
