name: Publish Docker image

on:
  release:
    types: [published]

env:
  RELEASE_TAG: ghcr.io/${{ github.repository_owner }}/access-guard:${{ github.event.release.tag_name }}
  LATEST_TAG: ghcr.io/${{ github.repository_owner }}/access-guard:latest

jobs:
  build_and_push:
    name: Build and push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.6.3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push images
        uses: docker/build-push-action@v2
        with:
          build-args: |
            BUILD_TARGET=release
            BUILD_VERSION=${{ github.event.release.tag_name }}
          push: true
          tags: |
            ${{ env.RELEASE_TAG }}
            ${{ env.LATEST_TAG }}
