name: Publish Docker image

on:
  release:
    type: [published]

jobs:
  build_and_push:
    name: Build and push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          build-args: |
            BUILD_TARGET=release
            SOURCE_COMMIT=${{ github.sha }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/access-guard:${{ github.event.release.tag_name }}
            ghcr.io/${{ github.repository_owner }}/access-guard:latest
